pipeline:
  name: CDK
  identifier: CDK
  projectIdentifier: Serverless
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: harness-cdk
        build: <+input>
  stages:
    - stage:
        name: Build - Test
        identifier: Build_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: RunTests
                  name: Unit Tests
                  identifier: Unit_Tests
                  spec:
                    language: Python
                    buildTool: Pytest
                    args: "--junitxml=out_report.xml"
                    runOnlySelectedTests: true
                    preCommand: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                      python3 -m pip install -r requirements-dev.txt
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - out_report.xml*
                    enableTestSplitting: false
    - stage:
        name: Deploy Dev
        identifier: Deploy_Dev
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: CDK Deploy
                  identifier: CDK_Deploy
                  steps:
                    - step:
                        type: GitClone
                        name: Git Clone
                        identifier: Git_Clone
                        spec:
                          connectorRef: account.Github
                          repoName: harness-cdk
                          build:
                            type: branch
                            spec:
                              branch: main
                    - step:
                        type: Run
                        name: Install Requirements
                        identifier: Install_Requirements
                        spec:
                          connectorRef: account.Dockerhub
                          image: python:latest
                          shell: Sh
                          command: |-
                            cd harness-cdk/
                            python3 -m pip install -r requirements.txt
                    - step:
                        type: AwsCdkSynth
                        name: CDK Synth
                        identifier: CDK_Synth
                        spec:
                          connectorRef: account.Dockerhub
                          image: harness/aws-cdk-plugin:1.0.0-python
                          appPath: harness-cdk
                        timeout: 10m
                    - step:
                        type: AwsCdkBootstrap
                        name: CDK Bootstrap
                        identifier: CDK_Bootstrap
                        spec:
                          connectorRef: account.Dockerhub
                          image: harness/aws-cdk-plugin:1.0.0-python
                        timeout: 10m
                    - step:
                        type: AwsCdkDiff
                        name: CDK Diff
                        identifier: CDK_Diff
                        spec:
                          connectorRef: account.Dockerhub
                          image: harness/aws-cdk-plugin:1.0.0-python
                        timeout: 10m
                    - step:
                        type: AwsCdkDeploy
                        name: CDK Deploy
                        identifier: CDK_Deploy
                        spec:
                          connectorRef: account.Dockerhub
                          image: harness/aws-cdk-plugin:1.0.0-python
                          provisionerIdentifier: hitcounter
                        timeout: 10m
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: account.Kind
                      namespace: harness-deploy
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
