pipeline:
  projectIdentifier: Serverless
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: harness-cdk
        build: <+input>
  stages:
    - stage:
        name: Deploy Dev
        identifier: Deploy_Dev
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: CDK Deploy
                  identifier: CDK_Deploy
                  steps:
                    - step:
                        type: GitClone
                        name: Git Clone
                        identifier: Git_Clone
                        spec:
                          connectorRef: account.Github
                          repoName: harness-cdk
                          build:
                            type: branch
                            spec:
                              branch: typescript
                    - step:
                        type: AwsCdkSynth
                        name: CDK Synth
                        identifier: CDK_Synth
                        spec:
                          connectorRef: account.Dockerhub
                          image: harness/aws-cdk-plugin:1.0.0
                          appPath: harness-cdk
                          exportTemplate: true
                        timeout: 10m
                    - step:
                        type: AwsCdkBootstrap
                        name: CDK Bootstrap
                        identifier: CDK_Bootstrap
                        spec:
                          connectorRef: account.Dockerhub
                          image: harness/aws-cdk-plugin:1.0.0
                          commandOptions:
                            - aws://123456789012/us-east-1
                          appPath: harness-cdk
                        timeout: 10m
                    - step:
                        type: AwsCdkDiff
                        name: CDK Diff
                        identifier: CDK_Diff
                        spec:
                          connectorRef: account.Dockerhub
                          image: harness/aws-cdk-plugin:1.0.0
                        timeout: 10m
                    - step:
                        type: AwsCdkDeploy
                        name: CDK Deploy
                        identifier: CDK_Deploy
                        spec:
                          connectorRef: account.Dockerhub
                          image: harness/aws-cdk-plugin:1.0.0
                          provisionerIdentifier: hitcounter
                        timeout: 10m
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: account.Kind
                      namespace: harness-deploy
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
  identifier: CDK_TypeScript
  name: CDK - TypeScript
